POST https://travel-flow-hackathon-2022.herokuapp.com/user/signup
Content-Type: application/json

{
    "email":"thinhngow@gmail.com",
    "name":"lmao",
    "password":"123"
}

###
POST https://travel-flow-hackathon-2022.herokuapp.com/user/signin
Content-Type: application/json

{
    "email":"ngophuthinh2001@gmail.com",
    "password":"123"
}

###

GET https://travel-flow-hackathon-2022.herokuapp.com/user/me
Authorization: LMAO eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NzIsImVtYWlsIjoibmdvcGh1dGhpbmgyMDAxQGdtYWlsLmNvbSIsIm5hbWUiOm51bGwsInJlcHV0YXRpb25Qb2ludCI6MCwiaWF0IjoxNjUyMDYyODQ5LCJleHAiOjE2NTI2Njc2NDl9.6DHogmGdpJcgUjNU10gsQh-Hf8hbdWDhb-eR1zaOZEs

###
GET http://localhost:3003/location?page=1&limit=3

###
GET https://travel-flow-hackathon-2022.herokuapp.com/location/1

###
# filter=hour,week,month
GET https://travel-flow-hackathon-2022.herokuapp.com/location/1/graph?filter=hour


### 
GET https://travel-flow-hackathon-2022.herokuapp.com/location/1/reviews?page=1&limit=10
###

POST https://travel-flow-hackathon-2022.herokuapp.com/location/1/reviews
Authorization: LMAO eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0aGluaG5nb3dAZ21haWwuY29tIiwiaWF0IjoxNjUyMDE5OTgyLCJleHAiOjE2NTI2MjQ3ODJ9.vC7qUNCu-dskpn4FLYvfbUSUOAINnlc1ifmV3Bq-00o
Content-Type: application/json

{
    "rating":5,
    "content":"LMAO LMAO LMAO"
}
### 
GET https://travel-flow-hackathon-2022.herokuapp.com/plan
Authorization: LMAO eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0aGluaG5nb3dAZ21haWwuY29tIiwiaWF0IjoxNjUyMDE5OTgyLCJleHAiOjE2NTI2MjQ3ODJ9.vC7qUNCu-dskpn4FLYvfbUSUOAINnlc1ifmV3Bq-00o

###
GET https://travel-flow-hackathon-2022.herokuapp.com/plan/1
Authorization: LMAO eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0aGluaG5nb3dAZ21haWwuY29tIiwiaWF0IjoxNjUyMDE5OTgyLCJleHAiOjE2NTI2MjQ3ODJ9.vC7qUNCu-dskpn4FLYvfbUSUOAINnlc1ifmV3Bq-00o


### 
POST https://travel-flow-hackathon-2022.herokuapp.com/plan
Authorization: LMAO eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0aGluaG5nb3dAZ21haWwuY29tIiwiaWF0IjoxNjUyMDE5OTgyLCJleHAiOjE2NTI2MjQ3ODJ9.vC7qUNCu-dskpn4FLYvfbUSUOAINnlc1ifmV3Bq-00o
Content-Type: application/json

{
    "name":"Hà Nội 30/4-1/5"
}

###

DELETE https://travel-flow-hackathon-2022.herokuapp.com/plan/2
Authorization: LMAO eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0aGluaG5nb3dAZ21haWwuY29tIiwiaWF0IjoxNjUyMDE5OTgyLCJleHAiOjE2NTI2MjQ3ODJ9.vC7qUNCu-dskpn4FLYvfbUSUOAINnlc1ifmV3Bq-00o

###

POST https://travel-flow-hackathon-2022.herokuapp.com/plan/1/location
Authorization: LMAO eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0aGluaG5nb3dAZ21haWwuY29tIiwiaWF0IjoxNjUyMDE5OTgyLCJleHAiOjE2NTI2MjQ3ODJ9.vC7qUNCu-dskpn4FLYvfbUSUOAINnlc1ifmV3Bq-00o
Content-Type: application/json

{
    "locationId":1,
    "date": "2022-05-08T15:40:56.247Z",
    "numberOfPeople":100
}

###

DELETE https://travel-flow-hackathon-2022.herokuapp.com/plan/1/location/2
Authorization: LMAO eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0aGluaG5nb3dAZ21haWwuY29tIiwiaWF0IjoxNjUyMDE5OTgyLCJleHAiOjE2NTI2MjQ3ODJ9.vC7qUNCu-dskpn4FLYvfbUSUOAINnlc1ifmV3Bq-00o

###

POST https://travel-flow-hackathon-2022.herokuapp.com/user/favorite
Authorization: LMAO eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0aGluaG5nb3dAZ21haWwuY29tIiwiaWF0IjoxNjUyMDE5OTgyLCJleHAiOjE2NTI2MjQ3ODJ9.vC7qUNCu-dskpn4FLYvfbUSUOAINnlc1ifmV3Bq-00o
Content-Type: application/json

{
    "locationId": 1
}

###
GET https://travel-flow-hackathon-2022.herokuapp.com/user/favorite?page=1&limit=10
Authorization: LMAO eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0aGluaG5nb3dAZ21haWwuY29tIiwiaWF0IjoxNjUyMDE5OTgyLCJleHAiOjE2NTI2MjQ3ODJ9.vC7qUNCu-dskpn4FLYvfbUSUOAINnlc1ifmV3Bq-00o

###
GET https://travel-flow-hackathon-2022.herokuapp.com/planlocation?page=1&limit=10
Authorization: LMAO eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0aGluaG5nb3dAZ21haWwuY29tIiwiaWF0IjoxNjUyMDE5OTgyLCJleHAiOjE2NTI2MjQ3ODJ9.vC7qUNCu-dskpn4FLYvfbUSUOAINnlc1ifmV3Bq-00o
